// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PickleIQ.Infrastructure.Data;

#nullable disable

namespace PickleIQ.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260531103105_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PickleIQ.Core.Entities.CoachingReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HtmlContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VideoJobId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VideoJobId")
                        .IsUnique();

                    b.ToTable("CoachingReports");
                });

            modelBuilder.Entity("PickleIQ.Core.Entities.RallySegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("EndSeconds")
                        .HasColumnType("float");

                    b.Property<double>("StartSeconds")
                        .HasColumnType("float");

                    b.Property<Guid>("VideoJobId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VideoJobId");

                    b.ToTable("RallySegments");
                });

            modelBuilder.Entity("PickleIQ.Core.Entities.VideoJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighlightFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VideoJobs");
                });

            modelBuilder.Entity("PickleIQ.Core.Entities.CoachingReport", b =>
                {
                    b.HasOne("PickleIQ.Core.Entities.VideoJob", "VideoJob")
                        .WithOne("CoachingReport")
                        .HasForeignKey("PickleIQ.Core.Entities.CoachingReport", "VideoJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VideoJob");
                });

            modelBuilder.Entity("PickleIQ.Core.Entities.RallySegment", b =>
                {
                    b.HasOne("PickleIQ.Core.Entities.VideoJob", "VideoJob")
                        .WithMany("RallySegments")
                        .HasForeignKey("VideoJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VideoJob");
                });

            modelBuilder.Entity("PickleIQ.Core.Entities.VideoJob", b =>
                {
                    b.Navigation("CoachingReport");

                    b.Navigation("RallySegments");
                });
#pragma warning restore 612, 618
        }
    }
}
